### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by zhr211** [wizdom13/RND-Pytorch#1]
Hello,

This is really nice pytorch edition. I want to do some research based on ur content. But when I run train.py, I met this problem. Do u have any ideas? Thank you so much!

GPU training:  False
Sticky actions:  True
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
ERROR: Couldn't open /anaconda3/envs/RND/lib/python3.6/site-packages/atari_py/atari_roms/montezuma_revenge.bin ...

**Comment by wizdom13** [comment]
Hello,
This is a problem related to the requirements. You have to install OpenAI Gym correctly.

**Comment by zhr211** [comment]
Thank you
