### ISSUE TITLE
How long will get out of room7

### ISSUE THREAD

**Issue by zhr211** [wizdom13/RND-Pytorch#2]
Hello wisdom,

Thank you for your pretty neat code. We learnt a lot from it. One question we are not sure how long will model get out of room 7? We stayed at room 7 for about 1 days, current global step is 6M, rewards still keep at 2500. We found from 400 points to 2500 points is pretty fast. But at 2500, it did not make any progress.

**Comment by wizdom13** [comment]
Hi Zhr211,

Make sure to use 128 workers.

**Comment by zhr211** [comment]
Thank you so much, I read paper again. Also found this issue, his best results is based on env 1024. I will try 128 first, hope get good results. initially consider buffer, I used 16, maybe problem is here.
